### ISSUE TITLE
Silly question about `Err` formatting

### ISSUE THREAD

**Issue by javierhonduco** [d-e-s-o/debuginfod#11]
Opening an issue for this one because I want to understand the intent of some parts of the code I might be misunderstanding.

https://github.com/d-e-s-o/debuginfod/blob/c407209c9b6b120659618695ee6d230cb462a07a/src/client.rs#L138

I don't think the `build_id` variable is being substituted here. Is this missing a `format!()` or is this intended? Thanks in advance!

**Comment by d-e-s-o** [comment]
Yes, good catch. That part should use `with_context` and `format!`.

**Comment by d-e-s-o** [comment]
Will fix this up. Ideally that would be caught by the linter, but I think that's still an open issue (https://github.com/rust-lang/rust-clippy/issues/10195; albeit one with a pull request, it seems).

**Comment by javierhonduco** [comment]
Awesome, thanks so much!
