### ISSUE TITLE
On success, return the server URL

### ISSUE THREAD

**Issue by javierhonduco** [d-e-s-o/debuginfod#8]
Sometimes it could be useful to know what debuginfod server returned success (e.g. to store long-term in case we need to re-download it later on, or for debugging purposes). Would this be something you would be ok with?

This could be implemented by changing the `fetch_debug_info` return type, and also return a struct with more information, including the server that returned the data.

**Comment by d-e-s-o** [comment]
Yes, we could return a more general `Response` object from `Client::fetch_debug_info` that includes this information, I think.

**Comment by javierhonduco** [comment]
Thanks for your reply! It's pretty odd, not sure what's going off... Will investigate more next week. Anyways, just pushed a PR for this feature 😄  https://github.com/d-e-s-o/debuginfod/pull/10
